#!/usr/bin/env python3
import random
from typing import Generator


def gen_event() -> Generator[tuple[str, str], None, None]:
    players = ["alice", "bob", "charlie", "dylan"]
    actions = ["run", "eat", "sleep", "grab", "move", "climb", "swim", "release", "use"]

    while True:
        yield (random.choice(players), random.choice(actions))



def next():
    pass


def main() -> None:
    pass


if __name__ == "__main__":
    main()

"""
next(), range(), len(), print(), import typing,
typing.Generator, import random, random.*

#######################
list of action
list of player

generator: gen_event() take 2 randomply and send them back
it work with yield

next() call gen_event() to return a tupple (name, action)

the main will generate 1000 event
then list of 10tuples generated git gen_event again

another generator: consume_event
randomly pick an element from the 10tuples, remove it, yield it until
the list is empty
must be used directly  in the for .. in ..
#######################
This exercise requires the use of generators with the yield keyword
to create data streams on the fly. You must implement generator
functions that produce values on-demand rather than storing everything
in memory.

Create an endless generator function gen_event() that picks a random
name from a list of players, and a random action from a list of
actions. Each time next() is called on this generator, it returns a
new event as a tuple (name, action).

From the main part of your script, loop a thousand times and display all
1000 events you get from your gen_event() .

Then create a list of ten tuples generated by gen_event() again.

Finally, create a new generator function consume_event that takes the
previously created list, randomly pick one of its elements, remove
it from the list, and yields it, until the list is empty. This generator
must be used directly in the for .. in .. construct.

###########################################################""

#!/usr/bin/env python3

import random
from typing import Generator


def gen_event() -> Generator[tuple[str, str], None, None]:
    players = ["alice", "bob", "charlie", "dylan"]
    actions = ["run", "eat", "sleep", "grab", "move", "climb", "swim", "release", "use"]

    while True:
        yield (random.choice(players), random.choice(actions))


def consume_event(events: list[tuple[str, str]]) -> Generator[tuple[str, str], None, None]:
    while len(events) > 0:
        idx = random.randint(0, len(events) - 1)
        event = events.pop(idx)
        yield event


def main() -> None:
    print("=== Game Data Stream Processor ===")

    # Part 1: 1000 generated events
    event_gen = gen_event()
    for i in range(1000):
        name, action = next(event_gen)
        print(f"Event {i}: Player {name} did action {action}")

    # Part 2: build list of 10 events
    events_list = []
    for _ in range(10):
        events_list.append(next(event_gen))

    print(f"Built list of 10 events: {events_list}")

    # Part 3: consume list using generator
    for event in consume_event(events_list):
        print(f"Got event from list: {event}")
        print(f"Remains in list: {events_list}")


if __name__ == "__main__":
    main()

"""
